### ISSUE TITLE
On-page translation form displays all site strings

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/l10n_client#3]
When I'm on a page, the "Page text" section of the on-page translation form displays way too many language strings, probably *all* strings of the site, and not only the strings of the current page. Example:

On the page `admin/dashboard` I see strings like `{current} of {total}`, `« Prev`, `width of border (integer)`, or `Australia/Brisbane`. These strings aren't on the Dashboard page (and neither in the Admin menu, I guess).

**Comment by indigoxela** [comment]
Hm... I think I misunderstood something, this is "works as designed"?

https://www.drupal.org/project/l10n_client/issues/2594605

Silly. Maybe I find a nifty way to do better filtering.

**Comment by olafgrabienski** [comment]
Oh wait, is there a "Works as designed" label on that Drupal issue?

**Comment by indigoxela** [comment]
> Oh wait, is there a "Works as designed" label on that Drupal issue?

:confused: 

So, you were right. There *are* unrelated strings. The reason was a wrong variable name in hook_init().

How would you like to test? Here's a [patch](https://github.com/backdrop-contrib/l10n_client/commit/5a5ec98b4426ce68968b31f21caf59f7fa6ca804.patch) of the latest commit.

Or you can also download the zip file of the latest dev version - this is the only commit since the last release.

The change is minimal: https://github.com/backdrop-contrib/l10n_client/commit/5a5ec98b4426ce68968b31f21caf59f7fa6ca804

**Comment by olafgrabienski** [comment]
Thank you very much for the quick reaction! The change is indeed minimal, so it was easy to patch the file manually. More important, it fixes the issue for me! At least, there are much less language strings now.
